version: '2'
services:
  CassandraSeed:
    scale: 1
    start_on_create: true
  Cassandra1:
    scale: 1
    start_on_create: true
  Cassandra3:
    scale: 1
    start_on_create: true
  Cassandra2:
    scale: 1
    start_on_create: true
